### ISSUE TITLE
opencv version 

### ISSUE THREAD

**Issue by wanghaisheng** [TonyLyu/Final#1]
i have tried opencv-2.4.13.2 there is error 
```
(py2.7) ➜  Final git:(master) ✗ python main.py           
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    import detector
  File "/Users/wanghaisheng/workspace/OCR/Final/detector.py", line 131, in <module>
    threshold = bin.produceThresholds(res)
  File "/Users/wanghaisheng/workspace/OCR/Final/bin.py", line 8, in produceThresholds
    threshold0 = Wolf(crop, 3, 18, 18, 0.05 + (0 * 0.35), 128)
  File "/Users/wanghaisheng/workspace/OCR/Final/bin.py", line 79, in Wolf
    max_s, map_m, map_s, img = calcLocalStats(img, map_m, map_s, winx, winy)
  File "/Users/wanghaisheng/workspace/OCR/Final/bin.py", line 23, in calcLocalStats
    im_sum, im_sum_sq = cv2.integral2(im, sqdepth=cv2.CV_64F)
TypeError: 'sqdepth' is an invalid keyword argument for this function
```

**Comment by TonyLyu** [comment]
Try using opencv 3.2. And in a few days, I will upload new codes for the project.

**Comment by wanghaisheng** [comment]
thx

**Comment by wanghaisheng** [comment]
anything update? @TonyLyu
